//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCSACHTRATRE
    {
        public int IDBCSachTre { get; set; }
        public System.DateTime NgayThangNam { get; set; }
        public Nullable<int> IDCuonSach { get; set; }
        public Nullable<int> IDPhieuMuon { get; set; }
        public Nullable<int> SoNgayTraTre { get; set; }
    
        public virtual CUONSACH CUONSACH { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
