//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCTINHHINHMUONSACH
    {
        public int IDCTBCMuonSach { get; set; }
        public int IDBCMuonSach { get; set; }
        public int IDLoaiSach { get; set; }
        public int SoLuotMuon { get; set; }
        public double TiLe { get; set; }
    
        public virtual BCTINHHINHMUONSACH BCTINHHINHMUONSACH { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
    }
}
