//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUTRA
    {
        public int IDCTPhieuTra { get; set; }
        public Nullable<int> IDPhieuTra { get; set; }
        public int IDCuonSach { get; set; }
        public Nullable<int> IDPhieuMuon { get; set; }
        public Nullable<int> SoNgayMuon { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
    
        public virtual CUONSACH CUONSACH { get; set; }
        public virtual PHIEUTRA PHIEUTRA { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
