//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUMUON
    {
        public int IDCTPhieuMuon { get; set; }
        public int IDPhieuMuon { get; set; }
        public int IDCuonSach { get; set; }
    
        public virtual CUONSACH CUONSACH { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
