//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_USERADMIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_USERADMIN()
        {
            this.USERADMINs = new HashSet<USERADMIN>();
        }
    
        public int IDAdmin { get; set; }
        public string HoTenAdmin { get; set; }
        public System.DateTime NgaySinhAdmin { get; set; }
        public string DiaChiAdmin { get; set; }
        public string EmailAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERADMIN> USERADMINs { get; set; }
    }
}
