//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIENPHAT
    {
        public int IDPhieuThu { get; set; }
        public Nullable<int> IDDocGia { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<decimal> SoTienThu { get; set; }
        public Nullable<decimal> ConLai { get; set; }
    
        public virtual THEDOCGIA THEDOCGIA { get; set; }
    }
}
