//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThuVienEntities : DbContext
    {
        public QuanLyThuVienEntities()
            : base("name=QuanLyThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BCSACHTRATRE> BCSACHTRATREs { get; set; }
        public virtual DbSet<BCTINHHINHMUONSACH> BCTINHHINHMUONSACHes { get; set; }
        public virtual DbSet<CT_BCTINHHINHMUONSACH> CT_BCTINHHINHMUONSACH { get; set; }
        public virtual DbSet<CT_PHIEUMUON> CT_PHIEUMUON { get; set; }
        public virtual DbSet<CT_PHIEUNHAPSACH> CT_PHIEUNHAPSACH { get; set; }
        public virtual DbSet<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual DbSet<CT_TACGIA> CT_TACGIA { get; set; }
        public virtual DbSet<CT_USERADMIN> CT_USERADMIN { get; set; }
        public virtual DbSet<CUONSACH> CUONSACHes { get; set; }
        public virtual DbSet<DAUSACH> DAUSACHes { get; set; }
        public virtual DbSet<LOAIDOCGIA> LOAIDOCGIAs { get; set; }
        public virtual DbSet<LOAISACH> LOAISACHes { get; set; }
        public virtual DbSet<PHIEUMUON> PHIEUMUONs { get; set; }
        public virtual DbSet<PHIEUNHAPSACH> PHIEUNHAPSACHes { get; set; }
        public virtual DbSet<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHATs { get; set; }
        public virtual DbSet<PHIEUTRA> PHIEUTRAs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TACGIA> TACGIAs { get; set; }
        public virtual DbSet<THEDOCGIA> THEDOCGIAs { get; set; }
        public virtual DbSet<USERADMIN> USERADMINs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
