//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CT_PHIEUNHAPSACH = new HashSet<CT_PHIEUNHAPSACH>();
            this.CUONSACHes = new HashSet<CUONSACH>();
        }
    
        public int IDSach { get; set; }
        public int IDDauSach { get; set; }
        public int IDTacGia { get; set; }
        public string NhaXB { get; set; }
        public int NamXB { get; set; }
        public int SoLuongTon { get; set; }
        public decimal GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAPSACH> CT_PHIEUNHAPSACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUONSACH> CUONSACHes { get; set; }
        public virtual DAUSACH DAUSACH { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
