//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEDOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEDOCGIA()
        {
            this.PHIEUMUONs = new HashSet<PHIEUMUON>();
            this.PHIEUTHUTIENPHATs = new HashSet<PHIEUTHUTIENPHAT>();
            this.PHIEUTRAs = new HashSet<PHIEUTRA>();
            this.USERS = new HashSet<USER>();
        }
    
        public int IDDocGia { get; set; }
        public string HoTenDG { get; set; }
        public System.DateTime NgaySinhDG { get; set; }
        public string DiaChiDG { get; set; }
        public string EmailDG { get; set; }
        public int IDLoaiDG { get; set; }
        public System.DateTime NgayLapThe { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public decimal TongNo { get; set; }
    
        public virtual LOAIDOCGIA LOAIDOCGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRA> PHIEUTRAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
