//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public int IDDocGia { get; set; }
    
        public virtual THEDOCGIA THEDOCGIA { get; set; }
    }
}
